### ISSUE TITLE
AttributeError: 'SMPLOutput' object has no attribute 'J'

### ISSUE THREAD

**Issue by 1015904089** [JiahuiLei/GART#5]
When I run this program, the following error occurs.
 s8maolab | INFO | Dec-13-16:37:57 | Optimization with ./profiles/zju/zju_30s.yaml   [solver.py:1389]
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Using predefined pose: da_pose
python-BaseException
Traceback (most recent call last):
  File "/.pycharm_helpers/pydev/pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/GART/solver.py", line 1390, in <module>
    _, optimized_seq = solver.run(data_provider)
  File "/GART/solver.py", line 786, in run
    ) = self._get_model_optimizer(betas=init_beta, add_bones_total_t=total_t)
  File "/GART/solver.py", line 181, in _get_model_optimizer
    template = get_template(
  File "/GART/lib_gart/templates.py", line 29, in get_template
    template = SMPLTemplate(
  File "/GART/lib_gart/templates.py", line 69, in __init__
    J_canonical, A0 = init_smpl_output.J, init_smpl_output.A
AttributeError: 'SMPLOutput' object has no attribute 'J'

**Comment by JiahuiLei** [comment]
Thanks for your interest. We modified a little bit the smplx library (which is already contained in this repo), so could you check that you are NOT using the original smplx library?  thanks
